import re
import json
from typing import Dict, List, Optional
from dataclasses import dataclass
from datetime import datetime


@dataclass
class ClaudeDetection:
    """Represents a detection of Claude in code."""
    repo_owner: str
    repo_name: str
    commit_sha: str
    commit_url: str
    author: str
    author_email: str
    commit_date: str
    commit_message: str
    detection_type: str
    evidence: str
    files_modified: List[str]
    copilot_enabled: bool = False
    additional_metadata: Optional[Dict] = None


class ClaudeDetector:
    """Detects Claude's presence in code and commits."""

    DEFAULT_CLAUDE_SIGNATURES = {
        "co_author": r"Co-Authored-By:\s*Claude\s*<[^>]+>",
        "claude_code": r"Generated with \[Claude Code\]",
        "claude_commit": r"🤖 Generated with.*Claude",
        "claude_email": r"<noreply@anthropic\.com>",
        "claude_ai_marker": r"(?i)(claude\.ai|anthropic\.com|claude-\d)",
        "cursor_claude": r"(?i)cursor.*claude",
        "cursor_ai": r"(?i)cursor ai",
        "copilot_claude": r"(?i)copilot.*claude",
    }

    DEFAULT_COMMIT_MESSAGE_PATTERNS = [
        r"(?i)generated (by|with|using) claude",
        r"(?i)claude assisted",
        r"(?i)co-authored.*claude",
        r"(?i)written (by|with) claude",
        r"(?i)ai generated.*claude",
        r"(?i)cursor.*claude",
        r"(?i)copied from claude",
        r"(?i)pasted from claude",
        r"(?i)claude\.ai chat",
        r"(?i)claude conversation",
        r"(?i)from anthropic",
    ]

    DEFAULT_CODE_PATTERNS = [
        r"@generated.*claude",
        r"(?i)// claude code",
        r"(?i)# claude code",
        r"(?i)/\* claude generated \*/",
        r"(?i)// from claude\.ai",
        r"(?i)# from claude\.ai",
        r"(?i)// cursor \+ claude",
        r"(?i)# cursor \+ claude",
        r"(?i)<!-- claude\.ai -->",
        r"(?i)<!-- generated by claude -->",
        r"(?i)// copied from claude chat",
        r"(?i)# copied from claude chat",
        r"(?i)// source: claude\.ai",
        r"(?i)# source: claude\.ai",
        r"(?i)// anthropic claude",
        r"(?i)# anthropic claude",
        r"(?i)TODO\(claude\)",
        r"(?i)TODO\(human\)",
        r"(?i)#\s*NOTE\s*\(claude\)",
        r"(?i)#\s*NOTE:\s*claude",
    ]

    CURSOR_SPECIFIC_PATTERNS = [
        r"(?i)\bcursor\s+(ide|ai|editor)\b",
        r"(?i)\bbuilt\s+with\s+cursor\b",
        r"(?i)\busing\s+cursor\b",
        r"(?i)\bgenerated\s+(by|with)\s+cursor\b",
        r"\.cursor/rules",
        r"\.cursor/settings",
        r"(?i)cursor-tutor",
        r"(?i)@cursor-?ai\b",
    ]

    COPILOT_PATTERNS = [
        r"(?i)github copilot",
        r"(?i)copilot generated",
        r"(?i)// copilot",
        r"(?i)# copilot",
    ]

    CLAUDE_FILE_SIGNALS = [
        "CLAUDE.md",
        ".claude/settings.json",
        ".claude/settings.local.json",
        ".claude/commands",
        ".claude/memory",
    ]

    CLAUDE_AUTHOR_PATTERNS = [
        r"(?i)claude\s+(sonnet|opus|haiku)",
        r"(?i)claude-code",
        r"(?i)^claude$",
    ]

    def __init__(self, custom_patterns: Optional[Dict] = None):
        """
        Initialize detector with optional custom patterns.

        Args:
            custom_patterns: Dictionary with custom detection patterns
                {
                    "signatures": {...},
                    "commit_patterns": [...],
                    "code_patterns": [...],
                    "cursor_patterns": [...],
                    "copilot_patterns": [...]
                }
        """
        self.detections: List[ClaudeDetection] = []
        self.copilot_cache: Dict[str, Dict] = {}

        if custom_patterns:
            self.CLAUDE_SIGNATURES = custom_patterns.get("signatures", self.DEFAULT_CLAUDE_SIGNATURES)
            self.COMMIT_MESSAGE_PATTERNS = custom_patterns.get("commit_patterns", self.DEFAULT_COMMIT_MESSAGE_PATTERNS)
            self.CODE_PATTERNS = custom_patterns.get("code_patterns", self.DEFAULT_CODE_PATTERNS)
            self.CURSOR_SPECIFIC_PATTERNS = custom_patterns.get("cursor_patterns", self.CURSOR_SPECIFIC_PATTERNS)
            self.COPILOT_PATTERNS = custom_patterns.get("copilot_patterns", self.COPILOT_PATTERNS)
        else:
            self.CLAUDE_SIGNATURES = self.DEFAULT_CLAUDE_SIGNATURES.copy()
            self.COMMIT_MESSAGE_PATTERNS = self.DEFAULT_COMMIT_MESSAGE_PATTERNS.copy()
            self.CODE_PATTERNS = self.DEFAULT_CODE_PATTERNS.copy()
            self.CURSOR_SPECIFIC_PATTERNS = self.CURSOR_SPECIFIC_PATTERNS.copy()
            self.COPILOT_PATTERNS = self.COPILOT_PATTERNS.copy()

    @classmethod
    def from_config_file(cls, config_path: str):
        """
        Create detector from configuration file.

        Args:
            config_path: Path to JSON configuration file

        Returns:
            ClaudeDetector instance
        """
        with open(config_path, 'r') as f:
            config = json.load(f)
        return cls(custom_patterns=config)

    def add_custom_signature(self, name: str, pattern: str):
        """Add a custom signature pattern."""
        self.CLAUDE_SIGNATURES[name] = pattern

    def add_custom_commit_pattern(self, pattern: str):
        """Add a custom commit message pattern."""
        self.COMMIT_MESSAGE_PATTERNS.append(pattern)

    def add_custom_code_pattern(self, pattern: str):
        """Add a custom code pattern."""
        self.CODE_PATTERNS.append(pattern)

    def set_copilot_status(self, repo_owner: str, repo_name: str, copilot_info: Dict):
        """
        Cache Copilot status for a repository.

        Args:
            repo_owner: Repository owner
            repo_name: Repository name
            copilot_info: Copilot status information
        """
        repo_key = f"{repo_owner}/{repo_name}"
        self.copilot_cache[repo_key] = copilot_info

    def get_copilot_status(self, repo_owner: str, repo_name: str) -> Optional[Dict]:
        """
        Get cached Copilot status for a repository.

        Args:
            repo_owner: Repository owner
            repo_name: Repository name

        Returns:
            Copilot status information if cached, None otherwise
        """
        repo_key = f"{repo_owner}/{repo_name}"
        return self.copilot_cache.get(repo_key)

    def analyze_file_tree(self, tree: list, repo_owner: str, repo_name: str) -> list:
        """
        Check repo file tree for Claude-specific files.

        Args:
            tree: List of tree item dicts from get_repo_tree()
            repo_owner: Repository owner
            repo_name: Repository name

        Returns:
            List of new ClaudeDetection objects found
        """
        all_paths = {item.get("path", "") for item in tree}
        new_detections = []

        for signal in self.CLAUDE_FILE_SIGNALS:
            matched_path = None
            if signal in all_paths:
                matched_path = signal
            elif signal == "CLAUDE.md":
                # Also match CLAUDE.md in subdirectories
                for path in all_paths:
                    if path.endswith("/CLAUDE.md"):
                        matched_path = path
                        break

            if matched_path:
                detection = ClaudeDetection(
                    repo_owner=repo_owner,
                    repo_name=repo_name,
                    commit_sha="",
                    commit_url="",
                    author="",
                    author_email="",
                    commit_date="",
                    commit_message="",
                    detection_type="claude_file_found",
                    evidence=f"Found Claude-specific file: {matched_path}",
                    files_modified=[matched_path],
                )
                self.detections.append(detection)
                new_detections.append(detection)

        return new_detections

    def analyze_author_name(self, commit: Dict, repo_owner: str, repo_name: str) -> Optional[ClaudeDetection]:
        """
        Check if a commit's author name matches a Claude agent pattern.

        Args:
            commit: Commit object from GitHub API
            repo_owner: Repository owner
            repo_name: Repository name

        Returns:
            ClaudeDetection if author name matches, None otherwise
        """
        commit_sha = commit.get("sha", "")
        commit_data = commit.get("commit", {})
        author_info = commit_data.get("author", {})
        author_name = author_info.get("name", "")

        for pattern in self.CLAUDE_AUTHOR_PATTERNS:
            if re.search(pattern, author_name):
                detection = ClaudeDetection(
                    repo_owner=repo_owner,
                    repo_name=repo_name,
                    commit_sha=commit_sha,
                    commit_url=commit.get("html_url", ""),
                    author=author_name,
                    author_email=author_info.get("email", ""),
                    commit_date=author_info.get("date", ""),
                    commit_message=commit_data.get("message", ""),
                    detection_type="claude_author_name",
                    evidence=f"Commit author name matches Claude pattern: {author_name!r}",
                    files_modified=[],
                )
                self.detections.append(detection)
                return detection

        return None

    def analyze_commit(self, commit: Dict, repo_owner: str, repo_name: str) -> Optional[ClaudeDetection]:
        """
        Analyze a commit for Claude signatures.

        Args:
            commit: Commit object from GitHub API
            repo_owner: Repository owner
            repo_name: Repository name

        Returns:
            ClaudeDetection if Claude is detected, None otherwise
        """
        commit_sha = commit.get("sha", "")
        commit_message = commit.get("commit", {}).get("message", "")
        commit_data = commit.get("commit", {})
        author_info = commit_data.get("author", {})
        author_name = author_info.get("name", "Unknown")
        author_email = author_info.get("email", "Unknown")
        commit_date = author_info.get("date", "Unknown")
        commit_url = commit.get("html_url", "")

        files_modified = []
        if "files" in commit:
            files_modified = [f.get("filename", "") for f in commit.get("files", [])]

        detection_type = None
        evidence = None

        for sig_name, pattern in self.CLAUDE_SIGNATURES.items():
            if re.search(pattern, commit_message):
                detection_type = f"signature_{sig_name}"
                evidence = f"Found pattern '{sig_name}' in commit message"
                break

        if not detection_type:
            for pattern in self.COMMIT_MESSAGE_PATTERNS:
                if re.search(pattern, commit_message):
                    detection_type = "commit_message_pattern"
                    evidence = f"Commit message matches Claude pattern: {pattern}"
                    break

        if not detection_type:
            for pattern in self.CURSOR_SPECIFIC_PATTERNS:
                if re.search(pattern, commit_message):
                    detection_type = "cursor_detected"
                    evidence = f"Cursor IDE reference found in commit message"
                    break

        if not detection_type:
            for pattern in self.COPILOT_PATTERNS:
                if re.search(pattern, commit_message):
                    detection_type = "copilot_detected"
                    evidence = f"GitHub Copilot reference found in commit message"
                    break

        copilot_status = self.get_copilot_status(repo_owner, repo_name)
        copilot_enabled = copilot_status.get("copilot_enabled", False) if copilot_status else False

        if detection_type:
            additional_metadata = {}
            if copilot_status:
                additional_metadata["copilot_info"] = copilot_status

            detection = ClaudeDetection(
                repo_owner=repo_owner,
                repo_name=repo_name,
                commit_sha=commit_sha,
                commit_url=commit_url,
                author=author_name,
                author_email=author_email,
                commit_date=commit_date,
                commit_message=commit_message,
                detection_type=detection_type,
                evidence=evidence,
                files_modified=files_modified,
                copilot_enabled=copilot_enabled,
                additional_metadata=additional_metadata if additional_metadata else None
            )
            self.detections.append(detection)
            return detection

        return None

    def analyze_code_content(self, content: str, commit: Dict, repo_owner: str, repo_name: str, filename: str) -> Optional[ClaudeDetection]:
        """
        Analyze code content for Claude signatures.

        Args:
            content: Code content as string
            commit: Commit object from GitHub API
            repo_owner: Repository owner
            repo_name: Repository name
            filename: Name of the file being analyzed

        Returns:
            ClaudeDetection if Claude is detected, None otherwise
        """
        commit_sha = commit.get("sha", "")
        commit_data = commit.get("commit", {})
        commit_message = commit_data.get("message", "")
        author_info = commit_data.get("author", {})
        author_name = author_info.get("name", "Unknown")
        author_email = author_info.get("email", "Unknown")
        commit_date = author_info.get("date", "Unknown")
        commit_url = commit.get("html_url", "")

        for pattern in self.CODE_PATTERNS:
            if re.search(pattern, content):
                detection = ClaudeDetection(
                    repo_owner=repo_owner,
                    repo_name=repo_name,
                    commit_sha=commit_sha,
                    commit_url=commit_url,
                    author=author_name,
                    author_email=author_email,
                    commit_date=commit_date,
                    commit_message=commit_message,
                    detection_type="code_pattern",
                    evidence=f"Found Claude marker in file {filename}: {pattern}",
                    files_modified=[filename]
                )
                self.detections.append(detection)
                return detection

        return None

    def get_detections(self) -> List[ClaudeDetection]:
        """Get all detections found."""
        return self.detections

    def clear_detections(self):
        """Clear all stored detections."""
        self.detections = []

    def get_detection_summary(self) -> Dict:
        """
        Get summary statistics of detections.

        Returns:
            Dictionary with summary statistics
        """
        total = len(self.detections)
        by_type = {}
        by_repo = {}
        copilot_enabled_count = 0
        repos_with_copilot = set()

        for detection in self.detections:
            detection_type = detection.detection_type
            by_type[detection_type] = by_type.get(detection_type, 0) + 1

            repo_key = f"{detection.repo_owner}/{detection.repo_name}"
            by_repo[repo_key] = by_repo.get(repo_key, 0) + 1

            if detection.copilot_enabled:
                copilot_enabled_count += 1
                repos_with_copilot.add(repo_key)

        return {
            "total_detections": total,
            "by_detection_type": by_type,
            "by_repository": by_repo,
            "repositories_affected": len(by_repo),
            "copilot_enabled_detections": copilot_enabled_count,
            "repositories_with_copilot": len(repos_with_copilot)
        }
